# unittest模块的基本使用
---
doctest简单易用，而unittest就显得灵活强大。它是JUnit的Python版, 因此也称为PyUnit。  

## 先看例子

**例一:**  

main.py, 要测试的为函数：
```python
def add(x, y):
    return x + y
def sub(x, y):
    return x - y
```
测试程序test.py
```python
import unittest  
import main
  
class mytest(unittest.TestCase):  
    # 初始化工作  
    def setUp(self):  
        pass  
    # 退出清理工作  
    def tearDown(self):  
        pass  
    # 具体的测试用例，一定要以test开头  
    def testsum(self):  
        self.assertEqual(main.add(1, 2), 3, 'test add fail')  
    def testsub(self):  
        self.assertEqual(main.sub(2, 1), 1, 'test sub fail')     
          
if __name__ =='__main__':  
    unittest.main()
```
  
**例二:**   

main.py，要测试的为类
```python
class myclass:
    def add(self, x, y):
        return x + y
    def sub(self, x, y):
        return x - y
```
测试程序，test.py: 
```python
import unittest  
import main
  
class mytest(unittest.TestCase):  
    # 初始化工作  
    def setUp(self):  
        self.testClass = main.myclass()  
    # 退出清理工作  
    def tearDown(self):  
        pass
    # 具体的测试用例，一定要以test开头  
    def testsum(self):  
        self.assertEqual(self.testClass.add(1, 2), 3, 'test add fail')  
    def testsub(self):  
        self.assertEqual(self.testClass.sub(2, 1), 1, 'test sub fail')     
          
if __name__ =='__main__':  
    unittest.main()
```
(切~ 这个例子和例一没什么区别嘛)  
确实，例二只是进一步说明用法。

**例三:**

main.py，要测试的类：
```python
class Widget:  
    def __init__(self, size = (40, 40)):  
        self._size = size  
    def getSize(self):  
        return self._size  
    def resize(self, width, height):  
        if width == 0  or height < 0:  
            raise ValueError, "illegal size"  
        self._size = (width, height)  
    def dispose(self):  # clear work
        pass
```
test.py，测试类：
```python
import unittest  
import main
  
class mytest(unittest.TestCase):  
     
    def setUp(self):  
        self.testClass = main.Widget() 
    def tearDown(self):  
        self.testClass.dispose()
        self.testClass = None
    def testSize(self):
        self.assertEqual(self.testClass.getSize(), (40, 4), "test Widget getSize() is  Error !")
    def testReSize(self):
        self.testClass.resize(100, 100)
        self.assertEqual(self.testClass.getSize(), (100, 100), "test Widget resize() is Error !")

def suite():
    suite = unittest.TestSuite()
    suite.addTest(mytest("testSize"))
    suite.addTest(mytest("testReSize"))
    return suite
          
if __name__ =='__main__':  
    unittest.TextTestRunner().run(suite())
```
这里suite()中还可以：  

	return unittest.makeSuite(mytest, "test")

这样用的前提是每个测试函数都必须要test开头。


## testunit基本用法

testunit用法最重要的是继承unittest.TestCase这个类，然后设置好setUp, tearDown 以及测试用例(必须以test开头)。  
然后就是用TestCase已经定义好的assertEqual进行测试了。  
除了assertEqual还有许多其他的函数：  

|Method	|Checks that	|New in |
|-------|---------------|-------|
|assertEqual(a, b)	|a == b	| | 
|assertNotEqual(a, b) |a != b | |
|assertTrue(x)	|bool(x) is True | |
|assertFalse(x) |bool(x) is False | |
|assertIs(a, b)	|a is b	|2.7 |
|assertIsNot(a, b)	|a is not b	|2.7 |
|assertIsNone(x)	|x is None	|2.7 |
|assertIsNotNone(x)	|x is not None	|2.7 |
|assertIn(a, b)	|a in b	|2.7 |
|assertNotIn(a, b) |a not in b	|2.7 |
|assertIsInstance(a, b)	|isinstance(a, b)	|2.7 |
|assertNotIsInstance(a, b) |not isinstance(a, b)	|2.7 |

在PyUnit测试框架中，TestSuite类可以看成是TestCase类的一个容器，用来对多个测试用例进行组织，这样多个测试用例可以自动在一次测试中全部完成。事实上，TestSuite除了可以包含TestCase外，也可以包含TestSuite，从而可以构成一个更加庞大的测试用例集：  
```python
suite1 = mysuite1.TheTestSuite()
suite2 = mysuite2.TheTestSuite()
alltests = unittest.TestSuite((suite1, suite2))
```
  
测试框架使用“TestRunner”类来为运行测试提供环境。最常用的TestRunner是TextTestRunner， 它可以以文字方式运行测试并报告结果。  
TextTestRunner默认将输出发送到sys.stderr，但是你可以通过向它的构造器传递一个不同的类似文件（file-object）对象来改变默认方式。  
如需在Python解释器会话中运行测试，这样使用TextTestRunner是一个理想的方法。

  
关于输出：
```
.F
======================================================================
FAIL: testSize (__main__.mytest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 18, in testSize
    self.assertEqual(self.testClass.getSize(), (40, 4), "test Widget getSize() is  Error !")
AssertionError: test Widget getSize() is  Error !

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
```
第一行中，“.”表示成功，“F”表示失败。他们是存在顺序的，这里表示第一个正确，第二个错误。之后会对错误的打出信息。
  
  
## 参考资料
> + [Python单元测试框架](http://pyunit.sourceforge.net/pyunit_cn.html)
> + [Python官方文档](https://docs.python.org/2/library/unittest.html#module-unittest)



